[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
itertools = "0.13.0"
indoc = "2.0.5"
regex = "1.11.1"
cached = "0.54.0"
priority-queue = "2.1.1"
