[package]
name = "aoc_2015"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
indoc = "2.0.4"
md5 = "0.7.0"
fancy-regex = "0.12.0"
lazy_static = "1.4.0"
regex = "1.10.2"
itertools = "0.12.0"
serde_json = "1.0.108"
