name: Test 2024

on:
  workflow_dispatch:
  push:
    paths:
      - "src/common/**"
      - "src/year2024/**"

env:
  YEAR: 2024

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test year${{ env.YEAR }}
